### ISSUE TITLE
You are not in an Ionic project directory. Project context may be missing.

### ISSUE THREAD

**Issue by AmitMY** [ionic-team/ionic-cli#5102]
**Description:**
The `ionic info` command says I am not in an ionic project, while I certainly am. 

**Steps to Reproduce:**
```bash
git clone https://github.com/sign/translate.git
cd translate
ionic info --verbose
```

**Output:**
```yaml
  ionic:lib Terminal info: { ci: false, shell: '/bin/zsh', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'info' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +1ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/Users/amitmoryossef/dev/sign/translate', version: '7.2.0' } +0ms
  ionic:lib:telemetry Sending telemetry for command: 'ionic info' [ '--verbose', '--interactive', '--color' ] +0ms
[WARN] You are not in an Ionic project directory. Project context may be missing.

Ionic:

   Ionic CLI : 7.2.0

Utility:

   cordova-res : 0.15.4
   native-run  : 2.0.1

System:

   NodeJS : v22.0.0
   npm    : 10.5.1
   OS     : macOS Unknown
```
